# bigip.tf manages F5's Big-IP AS3 for load balancing Consul services
#
# This file is autogenerated by Consul SNA. Any manul updates to this
# file will be clobbered. Once module count is supported by Terraform,
# this templated file will be merged with main.tf.

# provider "bigip" {
#   address  = var.bigip.address
#   username = var.bigip.username
#   password = var.bigip.password
# }

# module "bigip" {
#   source = "./modules/bigip"

#   address           = var.bigip.address
#   services          = [for name in var.service_mapping["bigip"] : var.services[name]]
# }
