variable "services" {
  description = "Consul services monitored by Consul NIA"
  type = map(object({
    # Name of the service
    name = string
    # Description of the service
    description = string
    # List of addresses for instances of the service
    addresses = list(string)
    # List of source addresses that initiates network communcation with
    # the service
    sources = list(string)
    # List of destination addresses that the service initiates network
    # communication with
    destinations = list(string)
  }))
}

variable tag_name {
  description = "The name of the tag to create and use for dynamic address group filtering of Consul service IPs"
  type        = string
  default     = "consul-nia"
}

variable consul_service_tags {
  description = "Adminstrative tags to add to Consul service address objects. These are existing tags on PAN-OS."
  type        = list(string)
  default     = []
}

variable address_group_tags {
  description = "Adminstrative tags to add to the address group for Consul service addresses. These are existing tags on PAN-OS."
  type        = list(string)
  default     = []
}

variable security_policy_rule_name {
  description = "Name of the security policy rule for managing Consul service addresses"
  type        = string
  default     = "consul-nia-security-policy"
}

variable security_policy_rule_description {
  description = "A text field, up to 1024 chracters, used to describe the rule"
  type        = string
  default     = "Security policy generated by Consul NIA to manage addresses of Consul services"
}

## Optional security profiles to configure the security policy
variable "profile_group" {
  type        = string
  description = "(Optional) Profile Setting: Group - The group profile name."
  default     = null
}

variable "profile_virus" {
  type        = string
  description = "(Optional) Profile Setting: Profiles - The antivirus setting."
  default     = null
}

variable "profile_spyware" {
  type        = string
  description = "(Optional) Profile Setting: Profiles - The anti-spyware setting."
  default     = null
}

variable "profile_vulnerability" {
  type        = string
  description = "(Optional) Profile Setting: Profiles - The Vulnerability Protection setting."
  default     = null
}

variable "profile_url_filtering" {
  type        = string
  description = "(Optional) Profile Setting: Profiles - The URL filtering setting."
  default     = null
}

variable "profile_file_blocking" {
  type        = string
  description = "(Optional) Profile Setting: Profiles - The file blocking setting."
  default     = null
}

variable "profile_wildfire_analysis" {
  type        = string
  description = "(Optional) Profile Setting: Profiles - The WildFire Analysis setting."
  default     = null
}

variable "profile_data_filtering" {
  type        = string
  description = "(Optional) Profile Setting: Profiles - The Data Filtering setting."
  default     = null
}
